export const FETCH_PRODUCTS = "FETCH_PRODUCTS" 
export const FETCH_PRODUCT = "FETCH_PRODUCT"
export const FETCH_BY_CATEGORY = "FETCH_BY_CATEGORY"
export const ADD_CART = "ADD_CART"
export const REMOVE_CART = "REMOVE_CART"
export const UPDATE_QUANTITY = "UPDATE_QUANTITY"
export const DELETE_CART = "DELETE_CART"


 